runtime:
  cache_dir: ./.cache/antora

site:
  title: Autoscaling applications with Openshift
  url: https://albertogd.github.io/rh-usal-ocp-22/index.html
  start_page: rh-usal-ocp-22::index.adoc

content:
  sources:
    - url: ./
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.0/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
